// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbzwhmfwkbseylxzufjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiendobWZ3a2JzZXlseHp1ZmpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNTY3NjQsImV4cCI6MjA2MjgzMjc2NH0.6RIIM51yokT4gk7rG4tifm_d0hYaE8OZvCwmCEglWFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);